version: "3.9"

services:
  aiueo_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: aiueo_server:1.1.0
    container_name: aiueo_server
    ports:
      - "8000:8000"
    networks:
      - aiueo_net
    restart: unless-stopped

networks:
  aiueo_net:
    external: true
